#!/bin/bash

if [ "$UID" -ne 0 ]; then
    sudo /usr/bin/4to6tunnelstop2
    exit $?
fi

source /etc/4to6tunnel2/conf.sh

ip addr del "$IP4TO6TUNNEL_IP4" dev ip4tunnel2
ip link set dev 4to6tunnel2 down
ip -6 tunnel del 4to6tunnel2

exit 0
